### ISSUE TITLE
Theme selection requires admin access?

### ISSUE THREAD

**Issue by patros** [datalust/seq-tickets#739]
We get "Could not load theme Unauthorized" message for users who aren't set as admins. In the latest docker image (2138-pre?)

**Comment by nblumhardt** [comment]
Ah! Oops, I've reproduced this, we'll have this patched in the next beta. Thanks Patrick!

**Comment by patros** [comment]
While I'm at it. The example style override under instance settings doesn't work because of the theme css selector. I had to do this for our dev/test instance `body.dark-theme .masthead,body.light-theme .masthead { background-color: orange; }`

**Comment by nblumhardt** [comment]
We had a bit of an epiphany and instead of changing the CSS suggestion, we've moved the `masthead` element:

![image](https://user-images.githubusercontent.com/342712/47826158-cb0f3c00-ddc1-11e8-9136-017ba50532fa.png)

Changing the top bar colour creates some pretty ugly visual issues, especially in the new version, so we're hoping this will be an improvement and "just work" for most people who will have used the default CSS suggestion.

What do you think?

**Comment by KodrAus** [comment]
We've fixed up the original issue attempting to change user preferences so will close this one off now. Please let us know if you find anything else!

**Comment by patros** [comment]
Thanks @nblumhardt and @KodrAus

**Comment by CumpsD** [comment]
This seems to still occur with `Seq 2023.1.9162`

![image](https://user-images.githubusercontent.com/1201644/231408410-d39d4389-7bc4-4a23-8a89-d911fd3db40a.png)

**Comment by nblumhardt** [comment]
Thanks for the heads-up, @CumpsD. It looks like the user has read-only permissions, currently this is understood to apply to all server-managed data, so they won't be able to change their user profile themselves.

**Comment by CumpsD** [comment]
Indeed, that seems to be the issue. Do you consider that a bug or as intended? Because I'd assume you would want to have the data read-only, not somebody's theme preferences, or password?

**Comment by nblumhardt** [comment]
It's currently as intended, but I think the choice we made here was wrong. I'll open a tracking issue to change this 👍

**Comment by CumpsD** [comment]
Thanks!
