### ISSUE TITLE
Problems consuming packages from Azure DevOps when authenticating with PATs

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#741]
Via: https://docs.getseq.net/v4.2/discuss/5bda8ea05fa411001312a778

We need to investigate/provide guidance on how to authenticate against VSTS feeds when installing app packages.

**Comment by nblumhardt** [comment]
It appears we should be able to authenticate using a random username, with a PAT as the password.

Is anyone doing this successfully with Azure DevOps?

**Comment by madacrobat** [comment]
I'm afraid the PAT solution isn't working to vsts. Still getting 401 but after a much longer delay (about 15 seconds). Haven't looked at the vsts logs but suspect they won't have anything interesting in them. I've created a local nuget feed on the seq server for now but this will be bit of an issue for us.

**Comment by nblumhardt** [comment]
Thanks for the feedback @madacrobat .

I'll pop this into our next patch milestone and try to make some progress on it :+1:

**Comment by nblumhardt** [comment]
We have some changes coming in the next patch (ideally next week) that improve our chances of succeeding with this. Instead of constructing URLs within the client, we stick more carefully to the the NuGet V3 protocol's hypermedia structure, and hopefully avoid touching any inaccessible URLs in the process.

**It'll be necessary to use a v3 feed endpoint for VSTS (on both Windows and Linux), random username, PAT as password.**

With a large dose of optimism, I'll close this, and re-open if the issue is reproducible in the new version.

**Comment by nblumhardt** [comment]
This has shipped in 5.1.3118

**Comment by madacrobat** [comment]
Looks like this is still failing with 401 using local TFS. V3 feed (ends with ..../nuget/v3/index.json), random username and PAT as password. This feed works fine in VS 2019 (and earlier). Sorry!

**Comment by nblumhardt** [comment]
Aw, snap! Thanks @madacrobat - reopening, will have to take another look.

**Comment by nblumhardt** [comment]
Having another try; is anyone following this able to test out a pre-release build?

**Comment by madacrobat** [comment]
Sorry, I should have replied yesterday. I'll try pre-release when you have it. BTW @nblumhardt, this is Ian from Skogsstyrelsen using  my personal GutHub account because I'm too lazy to logout and in again :-)

**Comment by nblumhardt** [comment]
Sent! Thanks @madacrobat 👍

**Comment by madacrobat** [comment]
Hi @nblumhardt but the same result (401) with the pre-release. Just a thought but when I create the PAT in TFS it says I need to use the generated token as the password rather than PAT as you suggested. Is that perhaps a clue to the problem? The problem with nuget access via TFS isn't on my critical list so whilst it would definitely be nice to have working I can live with a local nuget repository for now (I only have 1 app anyway at the moment).

**Comment by nblumhardt** [comment]
Argh - :-) ... thanks @madacrobat. We'll figure it out from here.

**Comment by nblumhardt** [comment]
Fixed in 5.1.3190

**Comment by CrossBound** [comment]
Sorry, this is still not working. In my case I'm attempting to authenticate against an in-house Azure DevOps server using a username and PAT.

I'm on Seq version 5.1.3200

![image](https://user-images.githubusercontent.com/11417093/71227686-a9169880-22a5-11ea-8d2e-662726a6d191.png)

![image](https://user-images.githubusercontent.com/11417093/71227770-e5e28f80-22a5-11ea-9890-56e7eaf9c1d6.png)

![image](https://user-images.githubusercontent.com/11417093/71227865-25a97700-22a6-11ea-84e0-0a883145d59c.png)

**Comment by CrossBound** [comment]
Any progress on this?

**Comment by nblumhardt** [comment]
Hi @CrossBound - thanks for the nudge, and sorry about the slow reply. I'll open a new ticket for this and link it here, as I suspect there's another issue we've missed.

One quick thing to try might be an update to 5.1.3364, since we fixed some API navigation issues in it with https://github.com/datalust/seq-tickets/issues/893, and these might also have generated 401s depending on the NuGet server being used.
